cdn 속도 테스트 기능 추가
sokcuri/TwimgSpeedPatch pull request #2
Opened 2019-06-09 08:24 UTC by RyuaNerin

2019-06-09 08:30 UTC, RyuaNerin commented
cross-platform 버전은 따로 작업 하고있어요

2019-06-09 08:58 UTC, sokcuri requested changes
리뷰 달아두었습니다. 확인 부탁드려요.

* 정규식 고치신게 제대로 작동하지 않을 가능성이 있습니다.
* 프로젝트가 현재 .NET Framework 2.0을 사용중인데 .NET Core 2.x 버전으로 올리는건 어떻게 생각하세요?
* 이미 리포지토리의 [server_ip.json](https://github.com/sokcuri/TwimgSpeedPatch/blob/master/data/server_ip.json) 에서 받아오는 IP를 무작위로 할당시킵니다. 이 IP는 twimg 모니터링 프로그램으로 안정화되었다고 판단된 IP를 넣어두었습니다. 
  * 패치 프로그램이 IP의 핑이나 리퀘스트를 검사하는 로직이 들어가지 않았으면 좋겠습니다. 패치를 누르면 직관적으로 Hosts 파일만 패치하고 싶습니다.
  * 위 기능들은 twimg 모니터링 프로그램에 넣는게 나을것 같습니다.
  * 랜덤으로 IP를 할당하는 케이스도 그대로 유지되었으면 합니다. 현재까지 노드들이 패치 전 테스트를 거쳐야할 만큼 유의미한 차이값을 보이진 않고 있습니다.
* Fody를 쓴다면 SimpleJSON을 쓸 이유가 없고 Newtonsoft.JSON을 쓰는건 괜찮은것 같습니다.
* 소스코드 클린업하고 정리해주셔서 감사합니다.

2019-06-09 08:58 UTC, sokcuri commented on TwimgSpeedPatch/HostFileManager.cs
> +        private static readonly Regex RegPattern = new Regex($@"^[^\s\t#].+[\s\t]+{HostName.Replace(".", "\\.")}.*$", RegexOptions.Singleline | RegexOptions.IgnoreCase | RegexOptions.Compiled);
> new Regex($@"^[^\s\t#].+[\s\t]+{HostName.Replace(".", "\\.")}.*$"

Hosts 파일에는 IP/호스트 페어 앞뒤로 탭이나 공백, 주석이 들어갈 수 있기 때문에 제대로 작동하지 않을 수 있습니다. 사용자가 앞뒤로 공백이나 주석을 달거나 한 경우면 동작하지 않을 수 있겠네요.

그리고 HostName에 Replace가 필요한가요? 안써도 잘 작동하길래요.

2019-06-09 08:58 UTC, sokcuri commented on TwimgSpeedPatch/Form1.cs
> +            if (MessageBox.Show("최적의 패치를 위하여 시간이 소요될 수 있습니다.\n계속할까요?", "알림", MessageBoxButtons.YesNo, MessageBoxIcon.Information) == DialogResult.No)
패치 프로그램에서 IP 상태나 핑을 따로 체크하지 않는 이유는 pbs.twimg.com 아이피를 깃허브 리포지토리에서 가져오기 때문이며, 어느정도 멀쩡한 노드만 선별해서 넣어두었기 때문입니다.

또한 가장 좋은 서버가 아닌 랜덤으로 IP를 패치하는 이유는 특정 노드에 사람들이 몰리면 문제가 생길 여지가 있기 때문입니다. Hosts 패치가 아니라 Custom DNS Resolver 프로그램이었다면 위와 같은 방식이 적합하겠지만, 서버에 쿼리를 때리고 핑쳐보는건 조금 회의적이네요. 그렇게 할 이유도 잘 안보이는것도 이유구요

2019-06-09 08:58 UTC, sokcuri commented on TwimgSpeedPatch/Form1.cs
> +                            errMsg = "오류가 발생하였습니다!\n\n" + task.Result;
아직은 패치해두지 않았는데 간혹 백신에서 Hosts 쓰기/액세스를 막는 경우가 발생합니다. 릴리즈 노트에 적어두었는데 시간나면 고칠게요

2019-06-09 08:58 UTC, sokcuri commented on TwimgSpeedPatch/Form1.cs
> -            Process.Start("https://twitter.com/sokcuri");
https://twitter.com/sokcuri 를 누르면 어디로 가지나요?

2019-06-09 08:58 UTC, sokcuri commented on TwimgSpeedPatch/HostFileManager.cs
> +        private const int RangeLastResolved = 365;
HttpTest 및 핑 테스트에 대한 부분은 위의 리뷰에도 적어두었지만, 최대한 패치 프로그램을 가볍게 만드는것을 선호합니다.

이 기능들은 지금 nodejs로 구현되어 있는 twimg 노드 모니터 프로그램에 들어가면 괜찮을것같은데 괜찮으시면 컨트리뷰트 넣어드릴게요

2019-06-09 08:58 UTC, sokcuri commented on TwimgSpeedPatch/HostFileManager.cs
> +                    // 추가일 경우 한줄 더 쓰기
패치 버튼을 눌렀을 때마다 다른 IP로 덧씌워지는건가요?

2019-06-09 08:58 UTC, sokcuri commented on TwimgSpeedPatch/TwimgSpeedPatch.csproj
> +    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
Fody 설정이 귀찮기도 했고 패치 프로그램이 Hosts 파일을 읽고 쓰고 여는것 외에는 다른 기능이 없어 단일 exe 파일로 만들려고 했는데. 이렇게 된다면 dotnet core로 올리는것도 생각해볼 수 있겠네요. (Cross-Platform 지원시)

2019-06-09 10:09 UTC, RyuaNerin commented on TwimgSpeedPatch/HostFileManager.cs
> +        private static readonly Regex RegPattern = new Regex($@"^[^\s\t#].+[\s\t]+{HostName.Replace(".", "\\.")}.*$", RegexOptions.Singleline | RegexOptions.IgnoreCase | RegexOptions.Compiled);
Regex 에서 `.` 는 any char 이니까 넣어줬습니다

2019-06-09 10:11 UTC, RyuaNerin commented on TwimgSpeedPatch/HostFileManager.cs
> +                    // 추가일 경우 한줄 더 쓰기
네 기존 데이터는 읽는 단계에서 지워집니다

2019-06-09 10:14 UTC, sokcuri commented on TwimgSpeedPatch/HostFileManager.cs
> +        private static readonly Regex RegPattern = new Regex($@"^[^\s\t#].+[\s\t]+{HostName.Replace(".", "\\.")}.*$", RegexOptions.Singleline | RegexOptions.IgnoreCase | RegexOptions.Compiled);
아 그러네 pbs.twimg.com에서 pbsatwimgbcom이어도 되겠네요 ㅋㅋ ..

2019-06-09 10:15 UTC, RyuaNerin commented on TwimgSpeedPatch/Form1.cs
> -            Process.Start("https://twitter.com/sokcuri");
링크라벨이 링크 연결 시켜주면서 웹브라우저를 열어주는걸로 기억했는데 동작하지 않네요...

2019-06-09 10:17 UTC, RyuaNerin commented on TwimgSpeedPatch/Form1.cs
> +            if (MessageBox.Show("최적의 패치를 위하여 시간이 소요될 수 있습니다.\n계속할까요?", "알림", MessageBoxButtons.YesNo, MessageBoxIcon.Information) == DialogResult.No)
차후 CDN 위치가 변경되거나 할때 매번 패치해주기가 귀찮아보여서 넣었습니다.

2019-06-09 10:17 UTC, RyuaNerin commented on TwimgSpeedPatch/HostFileManager.cs
> +        private const int RangeLastResolved = 365;
아 노드는 조금...

2019-06-09 10:40 UTC, sokcuri commented on TwimgSpeedPatch/HostFileManager.cs
> +        private const int RangeLastResolved = 365;
c#에는 custom dns resolver 구현이 없자나요 쉽게말해서 WebRequest를 때렸을때 지정한 Host 명에 따라서 다른 IP로 요청을 해야 하는데 못하니

2019-06-09 10:41 UTC, sokcuri commented on TwimgSpeedPatch/Form1.cs
> +            if (MessageBox.Show("최적의 패치를 위하여 시간이 소요될 수 있습니다.\n계속할까요?", "알림", MessageBoxButtons.YesNo, MessageBoxIcon.Information) == DialogResult.No)
초기버전은 아예 하드코딩해놨지만 지금은 json으로 빼뒀으니 상관없지 않을까요. 모니터링 부분만 자동화할 생각이었는데

2019-06-09 10:54 UTC, RyuaNerin commented on TwimgSpeedPatch/HostFileManager.cs
> +        private const int RangeLastResolved = 365;
dns resolver 가 없는게 좀 아쉽긴 한데 지정한 ip 로 http request 를 떄리는건 가능해요!

2019-06-09 10:56 UTC, RyuaNerin commented on TwimgSpeedPatch/HostFileManager.cs
> +        private const int RangeLastResolved = 365;
`https://__IP__/media/CgAc2lSUMAA30oE.jpg:orig` 로 reqeust 생성 후에 `HttpWebReqeust.Host` 프로퍼티 수정해주는식으로...

2019-06-09 11:55 UTC, sokcuri commented on TwimgSpeedPatch/Form1.cs
> -            Process.Start("https://twitter.com/sokcuri");
네 저도 안되서 넣어준건데 왜인지 모르겠어요

2019-06-09 11:56 UTC, sokcuri commented on TwimgSpeedPatch/HostFileManager.cs
> +        private const int RangeLastResolved = 365;
음 좀 많이 아쉽긴하네요 https인데 인증서에 써있는 도메인 아니라도 안튕겨내나요?

2019-06-09 18:23 UTC, RyuaNerin commented on TwimgSpeedPatch/HostFileManager.cs
> +        private const int RangeLastResolved = 365;
네 Host 랑 맞으니까 안팅겨내요.

2019-06-09 19:02 UTC, RyuaNerin commented on TwimgSpeedPatch/HostFileManager.cs
> +        private static readonly Regex RegPattern = new Regex($@"^[^\s\t#].+[\s\t]+{HostName.Replace(".", "\\.")}.*$", RegexOptions.Singleline | RegexOptions.IgnoreCase | RegexOptions.Compiled);
Regex 테스트시에는 문제가 없었는데 혹 다른 테스트케이스가 있을까요
[https://regex101.com/r/eAmepc/1](https://regex101.com/r/eAmepc/1)

2019-06-10 11:11 UTC, sokcuri commented on TwimgSpeedPatch/HostFileManager.cs
> +        private static readonly Regex RegPattern = new Regex($@"^[^\s\t#].+[\s\t]+{HostName.Replace(".", "\\.")}.*$", RegexOptions.Singleline | RegexOptions.IgnoreCase | RegexOptions.Compiled);
요기!
https://regex101.com/r/eAmepc/2

2019-06-11 08:28 UTC, RyuaNerin commented on TwimgSpeedPatch/HostFileManager.cs
> +        private static readonly Regex RegPattern = new Regex($@"^[^\s\t#].+[\s\t]+{HostName.Replace(".", "\\.")}.*$", RegexOptions.Singleline | RegexOptions.IgnoreCase | RegexOptions.Compiled);
`^[^\s\t#].+[\s\t]+pbs\.twimg\.com([\s\t]*)?$` 가 맞겠네요...

2019-06-11 08:34 UTC, RyuaNerin commented on TwimgSpeedPatch/HostFileManager.cs
> +        private static readonly Regex RegPattern = new Regex($@"^[^\s\t#].+[\s\t]+{HostName.Replace(".", "\\.")}.*$", RegexOptions.Singleline | RegexOptions.IgnoreCase | RegexOptions.Compiled);
`^[^\t #].+[\t ]+pbs\.twimg\.com(?:[\t ]+.*)?$`

2019-06-11 15:10 UTC, sokcuri commented
속도 테스트 기능을 빼고 PR 날려주실수 있나요?

2019-06-11 15:12 UTC, sokcuri commented on TwimgSpeedPatch/HostFileManager.cs
> +        private static readonly Regex RegPattern = new Regex($@"^[^\s\t#].+[\s\t]+{HostName.Replace(".", "\\.")}.*$", RegexOptions.Singleline | RegexOptions.IgnoreCase | RegexOptions.Compiled);
hosts에서는 앞에 공백이나 탭들어가도 인식되니
`^[^#].+[\t ]+pbs\.twimg\.com(?:[\t ]+.*)?$` 이 맞을것같아요

2019-06-12 00:18 UTC, RyuaNerin commented
속도테스트 기능을 빼면 다를게 없을것 같습니다 선생님

2019-06-12 00:35 UTC, sokcuri commented
PR 승인 못할것같네요 아예 생각하는게 다르다보니 ㅠㅠ

2019-06-12 00:35 UTC, closed without merging

2019-06-12 11:11 UTC, RyuaNerin commented
속도측정 기능을 포함된 프로그램은 [RyuaNerin/TwimgCdnPatch](https://github.com/RyuaNerin/TwimgCdnPatch) 으로 만들었습니다.